\c mydb

-- Create the ASYNC_MESSAGES table
CREATE TABLE IF NOT EXISTS ASYNC_MESSAGES (
  RECORD_ID SERIAL PRIMARY KEY,
  SENDER_NAME VARCHAR(30),
  MESSAGE VARCHAR(30),
  SENT_TIME TIMESTAMP,
  RECEIVED_TIME TIMESTAMP
);

GRANT SELECT, INSERT, UPDATE ON ASYNC_MESSAGES TO dist_user;
